"""Streamlit demo for the AI SOC Copilot.

    streamlit run app.py

Tabs: live triage queue · injection playground · IaC/container scan · eval results ·
deployed-AWS results.
"""
from __future__ import annotations

import json
import os

import pandas as pd
import streamlit as st

from attacks.payloads import ALL_PAYLOADS, inject
from data.synthetic_alerts import generate_batch
from defense.config import FULL, NAIVE
from pipeline.triage import triage_alert

st.set_page_config(page_title="AI SOC Copilot", layout="wide")
st.title("AI SOC Copilot — triage + guardrails + IaC security")

tab_queue, tab_attack, tab_iac, tab_results, tab_aws = st.tabs(
    ["Alert queue", "Injection playground", "IaC / container scan", "Eval results", "Deployed (AWS)"]
)

# --------------------------------------------------------------------------
with tab_queue:
    c = st.columns(3)
    n = c[0].slider("How many alerts", 3, 20, 6)
    guarded = c[1].toggle("Guardrails enabled", value=True)
    if c[2].button("Triage batch", type="primary"):
        rows = []
        prog = st.progress(0.0)
        batch = generate_batch(n, seed=7)
        for i, a in enumerate(batch, 1):
            r = triage_alert(a, config=FULL if guarded else NAIVE)
            rows.append({
                "alert_id": a.alert_id, "type": a.alert_type,
                "expected": a.expected_severity, "severity": r.severity,
                "confidence": r.confidence, "flagged": r.flagged_suspicious_input,
                "action": r.recommended_action[:80],
            })
            prog.progress(i / len(batch))
        st.dataframe(pd.DataFrame(rows), width="stretch")

# --------------------------------------------------------------------------
with tab_attack:
    payload = st.selectbox("Injection payload", ALL_PAYLOADS,
                           format_func=lambda p: f"{p['id']} — {p['technique']}")
    guarded2 = st.toggle("Guardrails enabled", value=True, key="atk_def")
    st.code(payload["text"], language="text")
    if st.button("Run attack", type="primary"):
        alert = generate_batch(1, seed=3)[0]
        base = alert.expected_severity
        alert.description = inject(alert.description, payload["text"])
        with st.spinner("Triaging injected alert…"):
            r = triage_alert(alert, config=FULL if guarded2 else NAIVE)
        c1, c2, c3 = st.columns(3)
        downgraded = r.severity in ("low", "medium") and r.severity != base
        c1.metric("Severity", r.severity, delta=f"baseline {base}",
                  delta_color="inverse" if downgraded else "off")
        c2.metric("Attack succeeded", "YES" if downgraded else "no")
        c3.metric("Flagged by guardrails", "yes" if r.flagged_suspicious_input else "no")
        st.write("**Summary:**", r.summary)
        st.write("**Recommended action:**", r.recommended_action)

# --------------------------------------------------------------------------
with tab_iac:
    st.caption("Checkov scans the vulnerable Terraform; Trivy scans outdated deps + the "
               "Dockerfile. Findings become alerts and flow through the same triage + guardrails.")
    kind = st.radio("Scanner", ["Terraform (Checkov)", "Container (Trivy)"], horizontal=True)
    if st.button("Scan + triage first 5 findings", type="primary"):
        try:
            if kind.startswith("Terraform"):
                from iac.scan import run_checkov, to_alerts
                findings = to_alerts(run_checkov())
            else:
                from containers.scan import scan_dependencies, to_alerts
                findings = to_alerts(scan_dependencies())
        except Exception as e:
            st.error(f"Scanner not available: {e}")
            findings = []
        st.write(f"**{len(findings)} findings** — triaging the first 5:")
        rows = []
        for a in findings[:5]:
            r = triage_alert(a, config=FULL)
            rows.append({"id": a.alert_id, "type": a.alert_type, "severity": r.severity,
                         "flagged": r.flagged_suspicious_input, "finding": a.description[:90]})
        if rows:
            st.dataframe(pd.DataFrame(rows), width="stretch")

# --------------------------------------------------------------------------
with tab_results:
    st.caption("Generated by `python run_attack_suite.py --all` + `eval.scorer.score_clean`.")
    try:
        st.image("eval/out/defense_ladder.png")
        col1, col2 = st.columns(2)
        col1.image("eval/out/before_after.png")
        col2.image("eval/out/per_technique.png")
        st.dataframe(pd.read_csv("eval/out/attack_results.csv"), width="stretch")
    except Exception as e:
        st.info(f"No eval artifacts yet ({e}). Run `python run_attack_suite.py --all`.")

# --------------------------------------------------------------------------
with tab_aws:
    st.caption("Live rows from the deployed `soc-copilot-alerts` DynamoDB table "
               "(profile `soc-copilot`, region us-east-1).")
    if st.button("Load from DynamoDB", type="primary"):
        try:
            import boto3
            sess = boto3.Session(profile_name="soc-copilot", region_name="us-east-1")
            items = sess.resource("dynamodb").Table("soc-copilot-alerts").scan().get("Items", [])
            if items:
                df = pd.DataFrame(items)[
                    [c for c in ["alert_id", "alert_type", "severity", "expected_severity",
                                 "flagged_suspicious_input", "confidence"] if c in items[0]]
                ]
                st.dataframe(df, width="stretch")
            else:
                st.info("Table is empty. Invoke the triage Lambda or run the ingest job.")
        except Exception as e:
            st.error(f"Could not read DynamoDB: {e}")
